# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Generates a release build artifact (nuget) from HEAD of master for beta Graph workload modules.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/Beta/*
    - config/ModulesMapping.jsonc
pr: none
variables:
  MODULE_PREFIX: 'Microsoft.Graph'
  WORKLOAD_MODULE_PATH: 'src\beta\'
  ARTIFACT_DIRECTORY: '$(Build.ArtifactStagingDirectory)\MGPowerShell\'
  AUTH_MODULE_PATH: 'src\Authentication\Authentication\bin\'
  AUTH_MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'
  MODULE_MAPPING_CONFIG_BETA_PATH: '$(System.DefaultWorkingDirectory)/config/ModulesMappingBeta.jsonc'

jobs:
- job: MSGraphPSSDKGeneration
  displayName: MS Graph PS SDK Beta Generation
  timeoutInMinutes: 600
  pool:
    vmImage: 'windows-latest'

  steps:
  # Install Node
  - task: NodeTool@0
    displayName: Node install
    inputs:
      versionSpec: '13.14.0'
  
  - task: Npm@1
    displayName: 'Install AutoRest'
    inputs:
      command: 'custom'
      customCommand: 'install -g autorest'
  
  - task: NuGetToolInstaller@1
    displayName: 'Install Nuget'
  
  - task: PowerShell@2
    displayName: 'Build Auth Modules'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateAuthenticationModule.ps1'
      arguments: '-RepositoryApiKey $(Api_Key) -Build -BuildWhenEqual'
      pwsh: true
  
  - task: PowerShell@2
    displayName: 'Generate and Build Graph Resource Modules'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateModules.ps1'
      arguments: '-RepositoryApiKey $(Api_Key) -Build'
      pwsh: true
    
  - task: PowerShell@2
    displayName: 'Pack Modules'
    inputs:
      targetType: 'inline'
      script: |
        [HashTable] $ModuleMapping = Get-Content $(MODULE_MAPPING_CONFIG_BETA_PATH) | ConvertFrom-Json -AsHashTable
        $ModuleMapping.Keys | ForEach-Object {
            $ModuleName = $_
            $ModuleProjectDir = "$(System.DefaultWorkingDirectory)/src/$ModuleName/$ModuleName"
            & $(System.DefaultWorkingDirectory)/tools/PackModule.ps1 -Module $ModuleName -ArtifactsLocation $(ARTIFACT_DIRECTORY)
        }
      pwsh: true
  
  # - task: PublishBuildArtifacts@1
  #   displayName: Publish Artifact Beta Modules
  #   inputs:
  #     PathtoPublish: '$(ARTIFACT_DIRECTORY)'
  #     ArtifactName: 'drop'
  #     publishLocation: 'Container'